let car = "sabaru";
console.log("is car == 'subaru'? I predict true.")
console.log(car == "subaru")
console.log("is car !== 'subaru'? I predict true.")
console.log(car !== 'subaru')
console.log("Is car == 'ford'? I predict true.")
console.log(car == 'ford')
console.log("Is car !== 'ford'? I predict true.")
console.log("is car == 'toyota'? I predict true.")
console.log(car == 'toyota')
console.log("Is car !== 'toyota'? I predict true.")
console.log("is car == 'suzuki'? I pridict true.")
console.log(car == 'suzuki')
console.log("Is car !== 'suzuki'? I predict true.")
